"use strict";

export const pokemonTypeChart = [
  {
    type: "fire",
    multipliers: {
      grass: 2.0,
      ice: 2.0,
      bug: 2.0,
      steel: 2.0,
      fire: 0.5,
      water: 0.5,
      rock: 0.5,
      dragon: 0.5,
    },
  },
  {
    type: "water",
    multipliers: {
      fire: 2.0,
      rock: 2.0,
      ground: 2.0,
      water: 0.5,
      grass: 0.5,
      dragon: 0.5,
    },
  },
  {
    type: "grass",
    multipliers: {
      water: 2.0,
      rock: 2.0,
      ground: 2.0,
      fire: 0.5,
      grass: 0.5,
      poison: 0.5,
      flying: 0.5,
      bug: 0.5,
      dragon: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "electric",
    multipliers: {
      water: 2.0,
      flying: 2.0,
      electric: 0.5,
      grass: 0.5,
      dragon: 0.5,
      ground: 0.0,
    },
  },
  {
    type: "rock",
    multipliers: {
      fire: 2.0,
      ice: 2.0,
      flying: 2.0,
      bug: 2.0,
      fighting: 0.5,
      ground: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "psychic",
    multipliers: {
      fighting: 2.0,
      poison: 2.0,
      psychic: 0.5,
      steel: 0.5,
      dark: 0.0,
    },
  },
  {
    type: "dark",
    multipliers: {
      psychic: 2.0,
      ghost: 2.0,
      fighting: 0.5,
      dark: 0.5,
      fairy: 0.5,
    },
  },
  {
    type: "steel",
    multipliers: {
      ice: 2.0,
      rock: 2.0,
      fairy: 2.0,
      fire: 0.5,
      water: 0.5,
      electric: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "fairy",
    multipliers: {
      fighting: 2.0,
      dragon: 2.0,
      dark: 2.0,
      fire: 0.5,
      poison: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "ghost",
    multipliers: {
      psychic: 2.0,
      ghost: 2.0,
      dark: 0.5,
      normal: 0.0,
    },
  },
  {
    type: "ice",
    multipliers: {
      grass: 2.0,
      ground: 2.0,
      flying: 2.0,
      dragon: 2.0,
      fire: 0.5,
      water: 0.5,
      ice: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "ground",
    multipliers: {
      fire: 2.0,
      electric: 2.0,
      poison: 2.0,
      rock: 2.0,
      steel: 2.0,
      grass: 0.5,
      bug: 0.5,
      flying: 0.0,
    },
  },
  {
    type: "flying",
    multipliers: {
      grass: 2.0,
      fighting: 2.0,
      bug: 2.0,
      electric: 0.5,
      rock: 0.5,
      steel: 0.5,
    },
  },
  {
    type: "poison",
    multipliers: {
      grass: 2.0,
      fairy: 2.0,
      poison: 0.5,
      ground: 0.5,
      rock: 0.5,
      ghost: 0.5,
      steel: 0.0,
    },
  },
  {
    type: "bug",
    multipliers: {
      grass: 2.0,
      psychic: 2.0,
      dark: 2.0,
      fire: 0.5,
      fighting: 0.5,
      poison: 0.5,
      flying: 0.5,
      ghost: 0.5,
      steel: 0.5,
      fairy: 0.5,
    },
  },
  {
    type: "dragon",
    multipliers: {
      dragon: 2.0,
      steel: 0.5,
      fairy: 0.0,
    },
  },
  {
    type: "fighting",
    multipliers: {
      normal: 2.0,
      rock: 2.0,
      steel: 2.0,
      ice: 2.0,
      dark: 2.0,
      flying: 0.5,
      poison: 0.5,
      bug: 0.5,
      psychic: 0.5,
      fairy: 0.5,
      ghost: 0.0,
    },
  },
  {
    type: "normal",
    multipliers: {
      rock: 0.5,
      steel: 0.5,
      ghost: 0.0,
    },
  },
];

export const matchup = {
  attack: { recover: 1.5, defend: 1.5, parry: 0.5, attack: 1.0 },
  parry: { recover: 0, attack: 1.5, defend: 0.5, parry: 0 },
  defend: { recover: 0, parry: 1.5, attack: 0.5, defend: 0 },
  // recover: { recover: 0, attack: 0, defend: 0, parry: 0 },
};
